name: learn-bithub-actions
on:
    workflow_dispatch:
        inputs:
            inputs_base:
                description: 'Enter the branch name'
                reqrired: true

jobs:
    check-bats-version:
        runs-on: ubuntu-latest
        steps:
            - run: echo "this is pen"